export const VALID_BIRDS = [
    "robin", "sparrow", "blue jay", "cardinal", "chickadee", 
    "eagle", "hawk", "owl", "hummingbird", "woodpecker", 
    "seagull", "pigeon", "crow", "raven", "finch",
    "dove", "starling", "bluebird", "cardinal", "goldfinch",
    "pelican", "flamingo", "penguin", "albatross", "osprey",
    "turkey vulture", "great blue heron", "bald eagle", 
    "red-tailed hawk", "barn owl", 
    "Sparrow, ", "Owl, ", "Plover, ", "Frigatebird, ", "Robin, ", "Magpie, ", "Shrike, ", "Harrier, ", "Blue Jay, ", "Kingfisher, ", "Myna, ", "Anhinga, ", "Finch, ", "Mockingbird, ", "Skylark, ", "Gannet, ", "Dove, ", "Crane, ", "Quail, ", "Shelduck, ", "Pigeon, ", "Vulture, ", "Starling, ", "Goshawk, ", "Crow, ", "Cormorant, ", "Jay, ", "Tanager, ", "Hawk, ", "Toucan, ", "Dipper, ", "Pheasant, ", "Eagle, ", "Osprey, ", "Pelican, ", "Nutcracker, ", "Hummingbird, ", "Puffin, ", "Ostrich, ", "Jacamar, ", "Cardinal, ", "Kiwi, ", "Emu, ", "Guineafowl, ", "Oriole, ", "Stork, ", "Hornbill, ", "Roller, ", "Chickadee, ", "Albatross, ", "Spoonbill, ", "Bulbul, ", "Woodpecker, ", "Loon, ", "Nuthatch, ", "Chaffinch, ", "Wren, ", "Sandpiper, ", "Bunting, ", "Titmouse, ", "Swallow, ", "Gull, ", "Nightjar, ", "Swamphen, ", "Seagull, ", "Peacock, ", "Rail, ", "Sandgrouse, ", "Pelican, ", "Lark, ", "Lapwing, ", "Oystercatcher, ", "Goose, ", "Eagle, ", "Grosbeak, ", "Grosbeak, ", "Duck, ", "Swallow, ", "Siskin, ", "Coot, ", "Parrot, ", "Raven, ", "Tern, ", "Lapwing, ", "Canary, ", "Rook, ", "Grouse, ", "Falconet, ", "Warbler, ", "Grebe, ", "Condor, ", "Jacana, ", "Falcon, ", "Cuckoo, ", "Egret, ", "Shoveler, ", "Heron, ", "Kestrel, ", "Weaver, ", "Pintail",
"Blue jay",
"Magpie",
"Goldfinch",
"Robin",
"Swallow",
"Starling",
"Pheasant",
"Toucan",
"Canary",
"Seagull",
"Heron",
"Potoo",
"Bush warbler",
"Barn swallow",
"Cassowary",
"Mallard",
"Common swift",
"Falcon",
"Megapode",
"Spoonbill",
"Osprey",
"Coot",
"Rail",
"Rudgerigar",
"Wren",
"Lark",
"Sandpiper",
"Arctic tern",
"Lovebird",
"Conure",
"Rallidae",
"Bee-eater",
"Grebe",
"Guinea fowl",
"Passerine",
"Albatross",
"Kiwi",
"Nightjar",
"Oilbird",
"Dodo",
"Azure dollar",
"Purple dollar",
"Greater coucal",
"Gannet",
"Thrush",
"Avocet",
"Catbird",
"Bluebird",
"Roadrunner",
"Dunnock",
"Northern cardinal",
"Teal",
"Northern shoveler",
"Gadwall",
"Northern pintail",
"Hoatzin",
"Kestrel",
"Oriole",
"Partridge",
"Tailorbird",
"Wagtail",
"Weaverbird",
"Skylark",
"Eagle",
"Duck",
"Hen",
"Parrot",
"Peacock",
"Dove",
"Stork",
"Swan",
"Pigeon",
"Goose",
"Pelican",
"Macaw",
"Parakeet",
"Finches",
"Crow",
"Raven",
"Vulture",
"Hawk",
"Crane	",
"Penguin",
"Hummingbird",
"Sparrow",
"Woodpecker",
"Hornbill",
"Owl",
"Myna",
"Cuckoo",
"Turkey",
"Quail",
"Ostrich",
"Emu",
"Cockatiel",
"Kingfisher",
"Kite",
"Cockatoo",
"Nightingale",
"Peregrine Falcon",
"Golden eagle",
"Resplendent Quetzal",
"Great tit",
"Blue tit",
"Long tailed tit",
"Coal tit"
].map(bird => bird.toLowerCase());
